const autos = [
  {
    escuderia: "Mercedes",
    pais: "Alemania",
    color: "Reino Unido",
    motor: "Mercedes",
    campeonatos: 8,
  },
  {
    escuderia: "Alpine",
    pais: "Reino Unido",
    color: "Negro",
    motor: "Renault",
    campeonatos: 2,
  },
  {
    escuderia: "HAAS",
    pais: "Estados Unidos",
    color: "Blanco",
    motor: "Ferrari",
    campeonatos: 0,
  },
  {
    escuderia: "Mclaren",
    pais: "Reino Unido",
    color: "Naranja",
    motor: "Mercedes",
    campeonatos: 8,
  },
  {
    escuderia: "Red Bull",
    pais: "Austria",
    color: "Azul marino",
    motor: "Honda",
    campeonatos: 5,
  },
  {
    escuderia: "Aston Martin",
    pais: "Reino Unido",
    color: "Verde",
    motor: "Mercedes",
    campeonatos: 0,
  },
  {
    escuderia: "Alpha Tauri",
    pais: "Italia",
    color: "Blanco y azul",
    motor: "Honda",
    campeonatos: 0,
  },
  {
    escuderia: "Ferrari",
    pais: "Italia",
    color: "Rojo",
    motor: "Ferrari",
    campeonatos: 16,
  },
  {
    escuderia: "Alfa Romeo",
    pais: "Italia",
    color: "Rojo y negro",
    motor: "Ferrari",
    campeonatos: 0,
  },
  {
    escuderia: "Williams",
    pais: "Reino Unido",
    color: "Azul",
    motor: "Mercedes",
    campeonatos: 0,
  },
];
